### PR TITLE
Added a message when accessing on a screen that isnt an ipad or ipad pro.

### PR DESCRIPTION
**Pull request by Carlos231**
A message will pop up when not on an ipad or ipad pro screen.

### CODE REVIEW

**Comment by Carlos231** [comment]
I fixed conflicts between my branch and main. Github thought there was repeats.

**Comment by Carlos231** [comment]
Please look over before approving

**Comment by Carlos231** [comment]
Testing done in chrome browser using inspect element and choosing ipad/ipad pro previews.

**Comment by kryolight** [comment]
The game now displays a message in a red box when not testing in Ipad mode. I'm not sure if it constantly be there when someone tries to play the game on another platform. There could be a timer that would make the message go away after a certain amount of time.

**Review by damonhuang233 — APPROVED** [review]

**Pull request merged**
