### PR TITLE
Issue1

### PR DESCRIPTION
**Pull request by Carlos231**

### CODE REVIEW

**Review by damonhuang233 — COMMENTED** [review]
Could you delete the file produce by IDEA such as./idea file and the target/ file in the files changed section?

**Comment by Carlos231** [comment]
Is there a way I could easily do this from the IDEA other than just deleting through github?

**Comment by damonhuang233** [comment]
You can write a .gitignore file, so it will ignore the file you want it to. I have one on my branch.

**Comment by 1mgroot** [comment]
looks all good

**Comment by Carlos231** [comment]
Resolved all merge conflicts

**Pull request merged**
